### ISSUE TITLE
Code block syntax and style updates

### ISSUE THREAD

**Issue by Jonic** [RaspberryPiFoundation/kramdown_rpf#35]
From @rik-cross, originally posted here: https://github.com/RaspberryPiFoundation/projects-ui/issues/1457

> Inline code can optionally have some lines highlighted using the following markdown:
> 
> `line_highlights: 3,5-6`
>
> We thought the syntax was highlight_lines: and so this syntax appears in some of our projects. Is it possible to change the syntax to save us having to go back through projects to amend?
>
> The highlighting that this syntax gives isn't clear enough, can the highlighting be made brighter?
> 
> Related: The filename at the top of the code block looks like code, or a broken file link. Can this text be made smaller, maybe to the top-right of the code and in a different font? so it is less confusing?
>
> --
>
> For 2 and 3 above we've suggested solutions but someone else might have a better idea of how to solve these problems.

**Comment by Jonic** [comment]
@rik-cross OH HI

1. Yes we can change `line_highlights` to `highlight_lines`. BUT I'd like to explain why I did it the way I did previously.

Firstly, so it matched the other settings pertaining to lines:

```ruby
line_numbers      = meta['line_numbers'] || false
line_number_start = meta['line_number_start'] || nil
line_highlights   = meta['line_highlights'] || nil
```

Secondly, `highlight_lines` indicates that we'll always be including one instance of highlighting many lines, where as `line_highlights` specifiess that we'll be including one or more __instances__ of highlighting. In the example you gave  of `3,5-6`, that specifies two highlights, not two lines. So in my head `line_highlights` made more sense that `highlight_lines`.

We can make this change/addition happen, but I wanted you to be completely clear on what that value is actually saying. Let us know what you'd like to happen.

2. Yep
3. Yep

The last two should be doable with some CSS tweaks, which I now rather ironically realise are best dealt with in projects-ui in the original issue I closed. I'll update that and address those there.

**Comment by gr-eg** [comment]
A cursory search only shows [1 repo which is using this feature](https://github.com/search?q=org%3Araspberrypilearning+highlight_lines&type=Code).

**Comment by Jonic** [comment]
@gr-eg And zero that are using `line_highlights`. So it's a safe change to make. Just wanted to set out my rationale for the way it was currently named.

**Comment by rik-cross** [comment]
@MarcScott If there's only 1 project including the highlighting syntax (see above), are you ok for us to manually update that project and leave the syntax as it is?

**Comment by MarcScott** [comment]
Yes - that's fine.

**Comment by rik-cross** [comment]
I'll close this... we can just update project syntax.
