### ISSUE TITLE
Translations not displaying

### ISSUE THREAD

**Issue by ninaszymor** [RaspberryPiFoundation/kramdown_rpf#37]
Previous translations of 'I need a hint' currently do not display. Instead, this is displayed: 

![image](https://user-images.githubusercontent.com/33628387/59220450-e7c3eb80-8bbc-11e9-9411-4a4d8a2491c4.png)

I checked 4 languages and all had this issue, even though they all have translations of kramdown_rpf>locales>en.yml.

**Comment by gr-eg** [comment]
Hi @ninaszymor, this is now fixed. I have just triggered a build for all the affected project so if you spot anymore do let us know.
